# READ MORE ABOUT configuration here https://merowing.info/Sourcery/usage.html
configurations:
    - sources:
        include:
          - iOS
      templates:
        - tools/Templates/
      output:
          path: iOSTests/Mocks/Generated
          link:
            project: ProtonPass.xcodeproj
            target: iOSTests
            group: iOSTests/Mocks/Generated
      args:
        testableImport: "Proton_Pass" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
        containedPathSubstringToApplyTemplate: "/iOS/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.
#    - sources:
#        include:
#          - LocalPackages/Client/Sources/Client
#      templates:
#        - tools/Templates/
#      output:
#          path: iOSTests/Mocks/Generated
#          link:
#            project: ProtonPass.xcodeproj
#            target: iOSTests
#            group: iOSTests/Mocks/Generated
#      args:
#        testableImport: "Client" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
#        containedPathSubstringToApplyTemplate: "/LocalPackages/Client/Sources/Client/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.
    - sources:
        include:
          - LocalPackages/Client/Sources/Client
      templates:
        - tools/Templates/
      output:
          path: LocalPackages/Client/Sources/ClientMocks
      args:
        imports:
            - "Client"
#        testableImport: "Client" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
        containedPathSubstringToApplyTemplate: "/LocalPackages/Client/Sources/Client/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.
    - sources:
        include:
          - LocalPackages/Core/Sources/Core
      templates:
        - tools/Templates/
      output:
          path: LocalPackages/Core/Sources/CoreMocks
      args:
        imports:
            - "Core"
#        testableImport: "Core" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
        containedPathSubstringToApplyTemplate: "/LocalPackages/Core/Sources/Core/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.
    - sources:
        include:
          - LocalPackages/UseCases/Sources/UseCases
      templates:
        - tools/Templates/
      output:
          path: LocalPackages/UseCases/Sources/UseCasesMocks
      args:
        imports:
            - "UseCases"
#            testableImport: "UseCases" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
        containedPathSubstringToApplyTemplate: "/LocalPackages/UseCases/Sources/UseCases/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.
